application: sa-auto-adder
version: 1
runtime: python
api_version: 1


handlers:
- url: /_wave/.*
  script: robot.py
- url: /favicon.ico
  static_files: webinterface/assets/favicon.ico
  upload: webinterface/assets/favicon.ico
- url: /.*
  script: webinterface/main.py
  
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?README$  